#include <catch2/catch_test_macros.hpp>
#include "libslic3r/PrintConfig.hpp"
using namespace Slic3r;

TEST_CASE("slicing_pipeline_plugin option exists and defaults empty", "[slicing_pipeline]") {
    DynamicPrintConfig cfg = DynamicPrintConfig::full_print_config();
    const ConfigOptionStrings* opt = cfg.option<ConfigOptionStrings>("slicing_pipeline_plugin");
    REQUIRE(opt != nullptr);
    CHECK(opt->values.empty());
    const ConfigOptionDef* def = cfg.def()->get("slicing_pipeline_plugin");
    REQUIRE(def != nullptr);
    CHECK(def->support_plugin == true);
    CHECK(def->gui_type == ConfigOptionDef::GUIType::plugin_picker);
}

#include "libslic3r/Print.hpp"

TEST_CASE("slicing pipeline hook setter is a no-op-safe injection", "[slicing_pipeline]") {
    int calls = 0;
    Slic3r::Print::set_slicing_pipeline_hook_fn(
        [&](Slic3r::Print&, const Slic3r::PrintObject*, Slic3r::SlicingPipelineStep){ ++calls; });
    Slic3r::Print::set_slicing_pipeline_hook_fn(nullptr); // reset — must be legal
    CHECK(calls == 0);
}

#include "test_data.hpp"
#include <vector>
#include <algorithm>
using namespace Slic3r::Test;

TEST_CASE("SlicingPipeline hook fires once per step per object in order", "[slicing_pipeline]") {
    struct Call { const Slic3r::PrintObject* obj; Slic3r::SlicingPipelineStep step; };
    std::vector<Call> calls;
    Slic3r::Print::set_slicing_pipeline_hook_fn(
        [&](Slic3r::Print&, const Slic3r::PrintObject* o, Slic3r::SlicingPipelineStep s){ calls.push_back({o, s}); });

    Slic3r::Print print; Slic3r::Model model;
    Slic3r::DynamicPrintConfig config = Slic3r::DynamicPrintConfig::full_print_config();
    config.set_key_value("slicing_pipeline_plugin", new Slic3r::ConfigOptionStrings({"probe"})); // activate
    init_print({TestMesh::cube_20x20x20}, print, model, config);
    print.process();
    Slic3r::Print::set_slicing_pipeline_hook_fn(nullptr);

    using S = Slic3r::SlicingPipelineStep;
    auto count = [&](S s){ return std::count_if(calls.begin(), calls.end(), [&](const Call& c){ return c.step == s; }); };
    CHECK(count(S::Slice) == 1);
    CHECK(count(S::Perimeters) == 1);
    CHECK(count(S::Infill) == 1);
    CHECK(count(S::WipeTower) == 1);
    CHECK(count(S::SkirtBrim) == 1);
    // print-wide steps carry a null object:
    for (const auto& c : calls)
        if (c.step == S::WipeTower || c.step == S::SkirtBrim) CHECK(c.obj == nullptr);
    // Slice must fire before Perimeters for the same object:
    auto idx = [&](S s){ for (size_t i=0;i<calls.size();++i) if (calls[i].step==s) return (int)i; return -1; };
    CHECK(idx(S::Slice) < idx(S::Perimeters));
}

#include <sstream>

TEST_CASE("Inactive hook: process output is byte-identical (no-op hook == unset)", "[slicing_pipeline]") {
    auto run = [](bool set_noop_hook) {
        Slic3r::Print print; Slic3r::Model model;
        auto config = Slic3r::DynamicPrintConfig::full_print_config();
        // NOTE: option left EMPTY -> plugin inactive regardless of hook presence.
        if (set_noop_hook)
            Slic3r::Print::set_slicing_pipeline_hook_fn([](Slic3r::Print&, const Slic3r::PrintObject*, Slic3r::SlicingPipelineStep){});
        else
            Slic3r::Print::set_slicing_pipeline_hook_fn(nullptr);
        init_print({TestMesh::cube_20x20x20}, print, model, config);
        std::string g = Slic3r::Test::gcode(print);
        Slic3r::Print::set_slicing_pipeline_hook_fn(nullptr);
        return g;
    };
    // Pre-existing nondeterminism unrelated to the hook makes a raw string compare
    // impossible: exported gcode embeds a wall-clock timestamp and ids derived from
    // the process-global ObjectID counter (never reset between runs) in a handful of
    // comment lines. Strip exactly those comment lines; every other byte -- all
    // motion/extrusion/temperature commands and all remaining comments -- is still
    // compared, so the assertion still proves the inactive hook leaves all
    // machine-meaningful output byte-identical.
    auto normalize = [](const std::string& gcode) {
        std::string out; out.reserve(gcode.size());
        std::istringstream in(gcode);
        std::string line;
        while (std::getline(in, line)) {
            if (line.compare(0, 15, "; generated by ") == 0) continue;    // wall-clock timestamp
            if (line.compare(0, 18, "; model label id: ") == 0) continue; // ObjectID-derived
            // "; [stop] printing object <name> id:N copy M" and
            // "; start/stop printing object, unique label id: N" (ObjectID-derived):
            if (line.find("printing object") != std::string::npos && line.find(" id:") != std::string::npos) continue;
            out += line; out += '\n';
        }
        return out;
    };
    CHECK(normalize(run(false)) == normalize(run(true))); // firing nothing (inactive) must not perturb slicing
}

TEST_CASE("Changing slicing_pipeline_plugin invalidates posSlice", "[slicing_pipeline]") {
    Slic3r::Print print; Slic3r::Model model;
    auto config = Slic3r::DynamicPrintConfig::full_print_config();
    init_print({TestMesh::cube_20x20x20}, print, model, config);
    print.process();
    REQUIRE(print.objects().front()->is_step_done(posSlice));
    config.set_key_value("slicing_pipeline_plugin", new Slic3r::ConfigOptionStrings({"probe"}));
    print.apply(model, config);
    CHECK_FALSE(print.objects().front()->is_step_done(posSlice)); // re-slice required
}
